# Generated by Django 3.2.10 on 2022-03-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0005_auto_20220302_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='customer',
            new_name='recommendations',
        ),
    ]
