# Generated by Django 3.2.10 on 2022-03-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0006_rename_customer_recommendation_recommendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='recommendations',
            new_name='customer',
        ),
    ]
